# Generated by Django 3.1.8 on 2023-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='experience',
            field=models.BooleanField(default=False),
        ),
    ]
