# Generated by Django 3.1.8 on 2023-11-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20230712_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='country',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='experience',
        ),
        migrations.AddField(
            model_name='lead',
            name='lost_amount',
            field=models.CharField(default=0, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='scam_company',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
