# Generated by Django 3.1.8 on 2023-11-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20231130_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='scam_company',
            field=models.CharField(default='noone', max_length=120),
        ),
    ]
