# Generated by Django 3.1.8 on 2023-11-30 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20231130_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='scam_company',
        ),
    ]
