# Generated by Django 3.1.8 on 2023-12-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_remove_lead_scam_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='company',
            field=models.CharField(default='idk', max_length=12),
        ),
    ]
