# Generated by Django 3.1.8 on 2023-12-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_lead_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(max_length=12),
        ),
    ]
